# Numpy进阶

In [1]:
# 环境初始化
import numpy as np

## Numpy数组的切片和索引进阶

### 一维数组的索引

In [29]:
a = np.arange(5) ** 2
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [30]:
# 基于下标的访问
a[3]

9

In [31]:
# 基于一定范围的下标
a[2:4]

array([4, 9], dtype=int32)

In [32]:
# 基于指定步长的访问 a[::2]  
# 冒号的作用 [开始:结束:步长]
a[0:5:2]

array([ 0,  4, 16], dtype=int32)

In [33]:
# 通过切片倒序取数据
a[::-1]

array([16,  9,  4,  1,  0], dtype=int32)

In [36]:
# 通过索引数组访问
index = np.array([2, 1, 3, 0])
a[index]

array([4, 1, 9, 0], dtype=int32)

### 二维数组的索引

In [7]:
a = np.arange(6).reshape(3, 2)
b = a+1
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# 取一行
b[1]

array([3, 4])

In [9]:
# 取一列  b[:,1]
b[:,1:2]

array([[2],
       [4],
       [6]])

In [10]:
# 取一个数字 == b[2][1]
b[2, 1]

6

### 复杂切片练习

- 练习1：

In [11]:
# 准备数据
a = np.arange(25)
a = a.reshape(5, -1) # (5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
# 切割红色数据, 7,8 a[1, 2:4]
a[1, 2:-1]

array([7, 8])

In [13]:
# 切割绿色数据 18,19,23,24
a[3:, 3:]

array([[18, 19],
       [23, 24]])

In [14]:
# 切割紫色区域，第二列 a[:,1] 数据维度塌陷
a[:, 1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [15]:
# 切割黄色区域
a[::2, 2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

- 练习2：

In [16]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# 切割红色区域, 0, 12, 24
a[[0, 2, 4], [0, 2, 4]]

array([ 0, 12, 24])

In [18]:
# 切割绿色区域 8,9  18,19  23,24
a[[1, 3, 4], 3:]

array([[ 8,  9],
       [18, 19],
       [23, 24]])

In [19]:
# 切割紫色区域 6,7,8
mask = np.array([False, True, True, True, False])
a[1, mask]

array([6, 7, 8])

In [20]:
# 切割黄色区域
a[[1, 4]][:, [0, 2, 3]]

array([[ 5,  7,  8],
       [20, 22, 23]])

## Numpy数组操作

### Numpy数组拆分

In [21]:
# 创建数组
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
# 垂直方向拆分
np.vsplit(a, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [23]:
# 水平方向拆分
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### 数组的合并

In [24]:
# 创建两个数组
a = np.array([[0, 1], [2, 3]])
b = np.array([[5, 6], [7, 8]])
print(a)
print(b)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


In [25]:
# 上下合并
np.vstack((a, b))

array([[0, 1],
       [2, 3],
       [5, 6],
       [7, 8]])

In [26]:
# 水平合并
np.hstack((a, b))

array([[0, 1, 5, 6],
       [2, 3, 7, 8]])