## 组合

In [2]:
from sympy import * #组合 
print(binomial(4, 2))

6


## numpy 创建数组

In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
# numpy 数组都是n维数组
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.random.random(3)

array([0.21403381, 0.16152539, 0.34393527])

In [9]:
# 推荐写法
np.array([1,2,3,4])
# 不推荐
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [11]:
# 错误写法
# np.array(1,2,3,4)

In [15]:
b = np.array([1,2,3,4.0])
b

array([1., 2., 3., 4.])

## 创建0-6的数组

In [16]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

创建-2到1间隔为0.5的数组, 前闭后开

In [17]:
np.arange(-2,1,0.5)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5])

等分空间为若干份

把0-2的空间分割成5份，包含2

In [18]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

## 二维数组

In [19]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
a = np.linspace(0,2,5)
a.shape

(5,)

In [22]:
b = np.ones([3,3])
b.shape

(3, 3)

In [23]:
np.ones([3,3,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
# 创建对角矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
## 创建指定数据的斜对角矩阵
a = np.array([1, 2, 3])
d = np.diag(a) # 2D的斜对角矩阵
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
d.ndim

2

In [30]:
d.shape

(3, 3)

In [32]:
d.size

9

In [34]:
d.dtype

dtype('int32')

In [35]:
np.linspace(0,2,5).dtype

dtype('float64')

In [36]:
b = np.array(['a',1,2,3])

In [37]:
b.dtype

dtype('<U1')

## 数据类型转换

In [39]:
a = np.array([1,2,3,4])
a.dtype

dtype('int32')

In [40]:
a.astype('float32')

array([1., 2., 3., 4.], dtype=float32)

## numpy矩阵的四则运算

In [41]:
a = np.array([1,2])
b = np.ones(2)
a+b

array([2., 3.])

In [42]:
a-b

array([0., 1.])

In [43]:
a*b

array([1., 2.])

In [45]:
a/a

array([1., 1.])

In [46]:
np.array([1,3,4,4])

array([1, 3, 4, 4])

In [47]:
np.array([1,3,4,4])*1.0

array([1., 3., 4., 4.])

In [50]:
a = np.array([1,3,4,4])
np.sqrt(a)

array([1.        , 1.73205081, 2.        , 2.        ])

In [51]:
a < 2

array([ True, False, False, False])

## 数据的索引

In [56]:
data = np.array([1,2,3,4])
data[0:]

array([1, 2, 3, 4])

In [57]:
#倒序索引
data[0:-2]

array([1, 2])

In [58]:
data.max()

4

In [59]:
data.min()

1

In [60]:
data.sum()

10

In [61]:
data.mean()

2.5

## numpy高维数组的切片

In [62]:
data = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [63]:
data[0,1]

2

In [67]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [72]:
data[0:2,0:1]

array([[1],
       [3]])

In [74]:
#矩阵的转置
data.T

array([[1, 3, 5],
       [2, 4, 6]])

## numpy的数据变形

In [75]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [76]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

## numpy 数据统计分析

In [79]:
a = np.array([
    [0,1],
    [2,3]
])

In [81]:
np.sum(a) # 全部元素求和

6

In [82]:
np.sum(a,axis=1) # axis=1代表按行求和

array([1, 5])

In [83]:
np.sum(a,axis=0) # axis=0代表按列求和

array([2, 4])

In [84]:
np.max(a,axis=1) #按行求最大值

array([1, 3])

In [85]:
np.max(a,axis=0) #按列求最大值

array([2, 3])

In [86]:
np.mean(a)

1.5

In [87]:
# 求中位数
np.median(a)

1.5

## 方差和标准差

In [88]:
a = np.array([1,2,3,4,5])
np.var(a)

2.0

In [89]:
np.std(a)

1.4142135623730951

## numpy随机数生成

* 生成0~1之间的随机数

In [98]:
np.random.rand(2,5)
# 2,5是随机数矩阵的形状

array([[0.51430676, 0.21084273, 0.57564192, 0.58630394, 0.16406801],
       [0.02073376, 0.87710352, 0.58494202, 0.63787672, 0.63773992]])

In [100]:
# 生成随机数(整数int类型), 前闭后开, 最后一个参数是数量
np.random.randint(2,6,10)

array([4, 2, 3, 3, 3, 5, 4, 2, 3, 2])

In [101]:
# 生成正态分布的随机数  , 默认以0为中心, 左右摆动
np.random.randn(1,10) 

array([[-1.7319605 , -1.39713339, -0.32257211, -1.16449142, -1.52193769,
         0.23457818, -0.06436515,  1.82157947,  1.2618892 ,  1.66108834]])

In [105]:
# 直接生成一定数量的[0,1) 区间范围的随机数
np.random.random_sample(10)

array([0.05537857, 0.13918003, 0.37111217, 0.52415686, 0.66135805,
       0.65530387, 0.27955468, 0.88045491, 0.35603823, 0.21933406])

## 正态分布相关API

*  创建符合正态分布的随机数

In [106]:
np.random.normal(85,10,size=(4,4))

array([[ 86.92940576,  98.68954565,  70.82335603,  93.60538518],
       [ 96.47259583,  89.72461329,  98.43345821, 107.87221255],
       [ 80.03714933,  68.60452833,  64.8102099 ,  79.89086559],
       [102.77421522,  76.27423498,  70.06464805,  88.36297077]])

* 创建一个期望为0, 标准的正态分布 

In [112]:
sample = np.random.randn(10000,10000)

In [113]:
# 计算采样数据的mean 平均值
sample.mean()

0.0001638397177674258

In [114]:
sample.std()

1.0000039060270658

## 数据打散

In [116]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [117]:
np.random.permutation(a)

array([14,  2, 25, 12, 22,  4, 20, 11, 13,  6, 28, 18,  7, 26, 10,  8, 19,
        9, 27,  5,  3, 16, 23, 21,  1, 24, 17, 29, 15,  0])

In [118]:
a
#注意, permutation方法打散数据不会修改数据本身

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [119]:
np.random.shuffle(a)

In [120]:
a

array([ 7, 22, 28, 18,  4, 15,  9, 12,  0, 26,  1,  6, 21,  2,  8, 10, 16,
       14,  3, 19, 17, 27, 25,  5, 20, 11, 29, 13, 23, 24])

In [121]:
np.random.seed(3)
np.random.randn(2,2)

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ]])

In [122]:
np.random.seed(3)
np.random.randn(2,2)

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ]])

In [123]:
np.random.seed(3)
np.random.randn(2,2)

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ]])

## numpy的逻辑操作

In [125]:
a = np.array([True,True, False,True,False])

* 判断是不是全都是True

In [126]:
np.all(a)

False

* 判断是不是至少有一个True

In [128]:
np.any(a)

True

* 把普通的numpy数组转换成真值数组

In [129]:
a = np.zeros((3,3))

In [134]:
a <= 0 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## numpy的排序操作

In [139]:
a  = np.random.randn(10)

In [140]:
a

array([ 0.98236743, -1.10106763, -1.18504653, -0.2056499 ,  1.48614836,
        0.23671627, -1.02378514, -0.7129932 ,  0.62524497, -0.16051336])

In [137]:
## 排序, 会直接修改数据源本身
a.sort()

In [138]:
a

array([-1.54647732, -1.31386475, -0.54535995, -0.47721803, -0.40467741,
       -0.04381817,  0.05003364,  0.88131804,  0.88462238,  1.70957306])

In [141]:
## 需求, 排序,但是不修改数据源本身
a.argsort()
## argsort返回的是从小到大排列后, 元素的下标

array([2, 1, 6, 7, 3, 9, 5, 8, 0, 4], dtype=int64)

In [149]:
a[a.argsort()]

array([-1.18504653, -1.10106763, -1.02378514, -0.7129932 , -0.2056499 ,
       -0.16051336,  0.23671627,  0.62524497,  0.98236743,  1.48614836])

In [150]:
a

array([ 0.98236743, -1.10106763, -1.18504653, -0.2056499 ,  1.48614836,
        0.23671627, -1.02378514, -0.7129932 ,  0.62524497, -0.16051336])

In [152]:
## 排序指定方式, 从小到大
b = np.random.randn(3,3)
b

array([[-1.02387576,  1.12397796, -0.13191423],
       [-1.62328545,  0.64667545, -0.35627076],
       [-1.74314104, -0.59664964, -0.58859438]])

In [153]:
b.sort(axis = 1) # axis按照行排序

In [155]:
b

array([[-1.02387576, -0.13191423,  1.12397796],
       [-1.62328545, -0.35627076,  0.64667545],
       [-1.74314104, -0.59664964, -0.58859438]])

In [156]:
help(b.sort)

Help on built-in function sort:

sort(...) method of numpy.ndarray instance
    a.sort(axis=-1, kind='quicksort', order=None)
    
    Sort an array, in-place.
    
    Parameters
    ----------
    axis : int, optional
        Axis along which to sort. Default is -1, which means sort along the
        last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be used, in the order in which
        they come up in the dtype, to break ties.
    
    See Also
    --------
    numpy.sort : Return a sorted copy of an array.
    argsort : Indirect sort.
    lexsort : Indirect stable sort on multiple keys.
    searchsorted :

# 行向量和列向量

In [158]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [159]:
a.T

array([1, 2, 3])

对于一维的矩阵(向量), 行向量和列向量在numpy表达的时候没有任何区别

对于二维的数组(矩阵), 行向量和列向量才会有区别

In [160]:
b = np.array([[1],[2],[3]])

In [162]:
b.shape

(3, 1)

In [163]:
b.T

array([[1, 2, 3]])

In [164]:
b.T.T

array([[1],
       [2],
       [3]])

## 把一维数组升级为二维数组

In [166]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])

## 计算PI的值

In [179]:
b = np.random.rand(99999999,2)
b

array([[0.01874521, 0.33563384],
       [0.7926538 , 0.44247139],
       [0.37401794, 0.98957716],
       ...,
       [0.87727687, 0.5905976 ],
       [0.22238359, 0.14579832],
       [0.40042305, 0.92902938]])

In [180]:
d = b ** 2
d

array([[3.51382736e-04, 1.12650074e-01],
       [6.28300040e-01, 1.95780933e-01],
       [1.39889420e-01, 9.79262963e-01],
       ...,
       [7.69614703e-01, 3.48805528e-01],
       [4.94544614e-02, 2.12571505e-02],
       [1.60338621e-01, 8.63095592e-01]])

In [181]:
e = np.sum(d,axis=1)
e

array([0.11300146, 0.82408097, 1.11915238, ..., 1.11842023, 0.07071161,
       1.02343421])

In [182]:
e<=1

array([ True,  True, False, ..., False,  True, False])

In [183]:
np.sum(e<=1)

78542811

In [185]:
4*np.sum(e<=1)/99999999

3.1417124714171245

## numpy数组的切片和索引

In [188]:
a = np.arange(5) ** 2
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [190]:
#基于下标访问
a[3]

9

In [194]:
#基于一定范围的下标访问
a[2:5]

array([ 4,  9, 16], dtype=int32)

In [195]:
# 按照指定的步长访问
a[::2]

array([ 0,  4, 16], dtype=int32)

In [199]:
# 三个冒号的作用  从哪个位置开始: 到哪个位置结束:步长
a[0:5:2]

array([ 0,  4, 16], dtype=int32)

In [200]:
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [201]:
a[::-1]  #倒序索引

array([16,  9,  4,  1,  0], dtype=int32)

## 2d数组的索引

In [205]:
a = np.arange(6).reshape(3,2)
b = a+1
b 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [206]:
## 取一行
b[1]

array([3, 4])

In [212]:
## 取一列
b[:,0:1]

array([[1],
       [3],
       [5]])

In [216]:
b[1,1] # b[1][1]

4

## 复杂切片练习

In [225]:
#准备数据
a = np.arange(0,25)
a = a.reshape(5,-1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [226]:
# 切割红色的数据, 7,8
a[1,2:4]

array([7, 8])

In [227]:
# 切割绿色区域, 18,19,23,24
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [230]:
# 切割紫色区域, 第二列
a[:,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [232]:
# 切割黄色的区域
a[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [233]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [234]:
## 切割第二个图的红色区域, 0,12,24
a[[0,2,4],[0,2,4]]

array([ 0, 12, 24])

In [235]:
a[(0,2,4),(0,2,4)]

array([ 0, 12, 24])

In [237]:
## 切割绿色区域 ,8,9  18,19  23,24
a[[1,3,4],3:]

array([[ 8,  9],
       [18, 19],
       [23, 24]])

In [238]:
# 切割紫色区域  6,7,8
filter = np.array([False,True,True,True,False])
a[1,filter]

array([6, 7, 8])

## numpy数组的数据拆分

In [241]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [242]:
# 按列的方向拆分
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [243]:
# 按行的方向拆分
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

## numpy的数据合并


In [245]:
a = np.array([[0,1],[2,3]])
a

array([[0, 1],
       [2, 3]])

In [246]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [248]:
# 上下合并
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [5, 6],
       [7, 8]])

In [250]:
# 水平合并
np.hstack((a,b))

array([[0, 1, 5, 6],
       [2, 3, 7, 8]])

## 根据索引去索引数组

In [252]:
a = np.arange(5) ** 2
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [253]:
b = np.array([3,3,2,2,1,3])
a[b]

array([9, 9, 4, 4, 1, 9], dtype=int32)

## numpy的广播机制

In [254]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [255]:
b = 1 
a + b

array([1, 2, 3])

In [256]:
a = np.arange(6).reshape(2, 3)
b = np.array([0, 1, 2])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [257]:
b

array([0, 1, 2])

In [258]:
a+b

array([[0, 2, 4],
       [3, 5, 7]])

In [259]:
## 矩阵的广播机制是有要求的
a = np.arange(6).reshape(2, 3)
b = np.array([0, 1, 2, 3])
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

## where(条件,x,y)

In [260]:
a = np.array([1,2,3,4,5,6,6,6,6,6])
a

array([1, 2, 3, 4, 5, 6, 6, 6, 6, 6])

In [262]:
# a!=6 条件, 满足条件,a的数据保留, 不满足条件,9
np.where(a!=6,a,9)

array([1, 2, 3, 4, 5, 9, 9, 9, 9, 9])

## 小案例 地铁票价查表

In [264]:
distance = np.array([0,2.7,3.9,4.9,8.6,10.1,12.7])
distance

array([ 0. ,  2.7,  3.9,  4.9,  8.6, 10.1, 12.7])

In [265]:
distance.reshape(7,1)

array([[ 0. ],
       [ 2.7],
       [ 3.9],
       [ 4.9],
       [ 8.6],
       [10.1],
       [12.7]])

In [268]:
table = distance - distance.reshape(7,1)
table

array([[  0. ,   2.7,   3.9,   4.9,   8.6,  10.1,  12.7],
       [ -2.7,   0. ,   1.2,   2.2,   5.9,   7.4,  10. ],
       [ -3.9,  -1.2,   0. ,   1. ,   4.7,   6.2,   8.8],
       [ -4.9,  -2.2,  -1. ,   0. ,   3.7,   5.2,   7.8],
       [ -8.6,  -5.9,  -4.7,  -3.7,   0. ,   1.5,   4.1],
       [-10.1,  -7.4,  -6.2,  -5.2,  -1.5,   0. ,   2.6],
       [-12.7, -10. ,  -8.8,  -7.8,  -4.1,  -2.6,   0. ]])

In [269]:
np.where(table>0,table,0)

array([[ 0. ,  2.7,  3.9,  4.9,  8.6, 10.1, 12.7],
       [ 0. ,  0. ,  1.2,  2.2,  5.9,  7.4, 10. ],
       [ 0. ,  0. ,  0. ,  1. ,  4.7,  6.2,  8.8],
       [ 0. ,  0. ,  0. ,  0. ,  3.7,  5.2,  7.8],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1.5,  4.1],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  2.6],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])