# Numpy高级

In [4]:
# 环境初始化
import numpy as np

## Numpy的广播机制

In [7]:
a = np.arange(3)
a

array([0, 1, 2])

In [8]:
b = 1
a + b

array([1, 2, 3])

In [9]:
a = np.arange(6).reshape(2, -1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b = np.array([0.1, 0.2, 0.3])
a + b

array([[0.1, 1.2, 2.3],
       [3.1, 4.2, 5.3]])

In [14]:
# Numpy 的广播机制是有要求的
a = np.arange(6).reshape(2, -1)
b =  np.array([0.1, 0.2, 0.3, 0.4])
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

## Where条件

- where(条件,x, y)

In [17]:
a = np.array([1, 2, 3, 4, 5, 6,6,6,6,6])

In [21]:
# a == 6 条件, 9 符合条件设置的值， a 不符合条件设定的值
np.where(a == 6, 9, a)

array([1, 2, 3, 4, 5, 9, 9, 9, 9, 9])

## Numpy矩阵基本运算



### 矩阵的乘法

In [46]:
# 买菜算账问题
a = np.array([[20, 5], [25, 10]])
b = np.array([[2], [1]])
np.dot(a, b)

array([[45],
       [60]])

In [47]:
# 鸡兔同笼问题
a = np.array([[1,1], [2, 4]])
b = np.array([35, 94])
np.linalg.solve(a, b)

array([23., 12.])

### 矩阵的逆

In [50]:
# 鸡兔同笼问题
a = np.array([[1,1], [2, 4]])
b = np.array([35, 94])
np.linalg.inv(a) @ b

array([23., 12.])